### ISSUE TITLE
Simulation hangs during update of wind data

### ISSUE THREAD

**Issue by oledahle** [USEPE-SesarJU/bluesky#24]
Often (but not always!) the simulator hangs at time 04:59, when updating wind data for cells.
Reproduction steps:
1) Check out exercise_3 branch of scenarios
2) Set config file in usepe_plugin.py to be <scenarios>/scenario/USEPE/exercise_3/settings_exe_3_d2c2.cfg
3) Launch BlueSky and start simulation by issuing the command "plugin load usepe"

Error output:
---
Staring to process wind data.
Processing wind data is DONE.
Assigning wind data to cells:
  0%|                                                                                                                                                | 2/2354 [00:00<00:13, 174.50it/s]
Traceback (most recent call last):
  File "BlueSky.py", line 134, in <module>
    main()
  File "BlueSky.py", line 101, in main
    bs.net.run()
  File "/home/oda/ws/bluesky/bluesky/network/node.py", line 67, in run
    bs.sim.step()
  File "/home/oda/ws/bluesky/bluesky/simulation/simulation.py", line 82, in step
    simtime.preupdate()
  File "/home/oda/ws/bluesky/bluesky/core/simtime.py", line 67, in preupdate
    fun.trigger()
  File "/home/oda/ws/bluesky/bluesky/core/simtime.py", line 209, in call_timed
    self._callback()
  File "/home/oda/ws/bluesky/plugins/usepe_plugin.py", line 153, in preupdate
    usepesegments.preupdate()
  File "/home/oda/ws/bluesky/plugins/usepe_plugin.py", line 449, in preupdate
    updated, self.segments = self.dynamicSegments()
  File "/home/oda/ws/bluesky/plugins/usepe_plugin.py", line 336, in dynamicSegments
    self.segmentation_service.update_wind_strat( wind_file, False )  # strategic update rules based on wind data
  File "/home/oda/ws/bluesky/usepe/segmentation_service/segmentation_service.py", line 315, in update_wind_strat
    wind_max = cellWind.max().to_numpy()
  File "/home/oda/.conda/envs/usepeosm/lib/python3.8/site-packages/xarray/core/_reductions.py", line 1316, in max
    return self.reduce(
  File "/home/oda/.conda/envs/usepeosm/lib/python3.8/site-packages/xarray/core/dataarray.py", line 2920, in reduce
    var = self.variable.reduce(func, dim, axis, keep_attrs, keepdims, **kwargs)
  File "/home/oda/.conda/envs/usepeosm/lib/python3.8/site-packages/xarray/core/variable.py", line 1848, in reduce
    data = func(self.data, **kwargs)
  File "/home/oda/.conda/envs/usepeosm/lib/python3.8/site-packages/xarray/core/duck_array_ops.py", line 341, in f
    return func(values, axis=axis, **kwargs)
  File "/home/oda/.conda/envs/usepeosm/lib/python3.8/site-packages/xarray/core/nanops.py", line 86, in nanmax
    return module.nanmax(a, axis=axis)
  File "/home/oda/.conda/envs/usepeosm/lib/python3.8/site-packages/xarray/core/nputils.py", line 157, in f
    result = getattr(npmodule, name)(values, axis=axis, **kwargs)
  File "<__array_function__ internals>", line 180, in nanmax
  File "/home/oda/.conda/envs/usepeosm/lib/python3.8/site-packages/numpy/lib/nanfunctions.py", line 476, in nanmax
    res = np.fmax.reduce(a, axis=axis, out=out, **kwargs)
ValueError: zero-size array to reduction operation fmax which has no identity

**Comment by mbaena-nommon** [comment]
Might be a problem on the python libraries version (we experienced similar problems).

In order to discard troubles in the wind data, please try with [scenario 1 dataset](https://isdefe-es.sharefile.com/d-sd57a7bfd86774e6482ba9db357c1b9b1)

If you keep experiencing the same problem, upgrade numpy to 1.23.2 and Shapely to 1.8.2.

**Comment by oledahle** [comment]
I tried with the wind data for exercise 1, and got the same result. I already have numpy version 1.23.2 and shapely version 1.8.4.

**Comment by mbaena-nommon** [comment]
The error seems associated with the xarray library. We had to install it for the first time when including this part of the code. IS your xarray version 2022.6.0? If not, please upgrade and try again. 

If this does not solve the problem, it might be because of the version of another package. You can upgrade all to the latest version with the command in [this page](https://www.activestate.com/resources/quick-reads/how-to-update-all-python-packages/). Note that upgrading a package might create conflicts in other projects you are working on, if they require a specific version.

**Comment by oledahle** [comment]
All packages updated according to the recipe above, but it still fails with the same error.

**Comment by oledahle** [comment]
The error does not occur if the with_path for the segmentation service is set to the "nest 01" file, like this:

[Segmentation_service]
wind_path = exercise_3_surveillance/USEPE_S3_3d_nest.1
