### ISSUE TITLE
USEPE plugin fails when adding non-UTM traffic

### ISSUE THREAD

**Issue by oledahle** [USEPE-SesarJU/bluesky#26]
If a scenario adds an aircraft without submitting a plan to the USEPE path planning, the usepe plugin fails calcWptDict().
To reproduce:
1) Start the USEPE plugin
2) call another scenario file to add an unrelated aircraft
(Example scenario files attached.)

Error message from BlueSky:
---
pdating segments...
Assigning segments...
Updating segment velocity...
No geovectoring rules
Updating travel times...
Dynamic segments completed
Loading wind in the simulation. File /home/oda/ws/bluesky/scenario/USEPE_S1_3d_nest01_5m_0s.scn
Completed
Origin or destination is not allowed, so the flight plan is rejected
Origin or destination is not allowed, so the flight plan is rejected
Origin or destination is not allowed, so the flight plan is rejected
Traceback (most recent call last):
  File "BlueSky.py", line 134, in <module>
    main()
  File "BlueSky.py", line 101, in main
    bs.net.run()
  File "/home/oda/ws/bluesky/bluesky/network/node.py", line 67, in run
    bs.sim.step()
  File "/home/oda/ws/bluesky/bluesky/simulation/simulation.py", line 82, in step
    simtime.preupdate()
  File "/home/oda/ws/bluesky/bluesky/core/simtime.py", line 67, in preupdate
    fun.trigger()
  File "/home/oda/ws/bluesky/bluesky/core/simtime.py", line 209, in call_timed
    self._callback()
  File "/home/oda/ws/bluesky/plugins/usepe_plugin.py", line 94, in preupdate
    usepesegments.preupdate()
  File "/home/oda/ws/bluesky/plugins/usepe_plugin.py", line 523, in preupdate
    self.calcWptDict()
  File "/home/oda/ws/bluesky/plugins/usepe_plugin.py", line 416, in calcWptDict
    wpt_route_graph = usepeflightplans.route_dict[acid]
KeyError: 'TR556'
[
[main_scenario.scn.txt](https://github.com/USEPE-SesarJU/bluesky/files/9563371/main_scenario.scn.txt)
[turkish.scn.txt](https://github.com/USEPE-SesarJU/bluesky/files/9563376/turkish.scn.txt)
](url)

**Comment by oledahle** [comment]
Maybe we can add an extra command to USEPE plugin to ignore certain aircraft? (These should not be diverted by conflict resolution either, as we can not assume that the UTM system can control them.)
For example USEPE ignore <ACID> ?

**Comment by oledahle** [comment]
Joakim is working on a fix for this.

**Comment by joakimrydberg** [comment]
Non-UTM traffic for surveillance exercise integrated after f33b227106356b6a9d9062b879df9ff659eacd15
