### ISSUE TITLE
Simulation fails / runs out of memory when processing wind data

### ISSUE THREAD

**Issue by oledahle** [USEPE-SesarJU/bluesky#27]
The usepe plugin tries to allocate 42 GB of memory when processing the wind data for exercise 3. That is too much for most normal computers...

To reproduce:
1) Run D2-C2 scenario using config settings for exercise 3 (attached)
Observe out-of memory error.
[main_scenario.scn.txt](https://github.com/USEPE-SesarJU/bluesky/files/9566746/main_scenario.scn.txt)

Error log from simulator:
---
Staring to process wind data.
Traceback (most recent call last):
  File "BlueSky.py", line 134, in <module>
    main()
  File "BlueSky.py", line 101, in main
    bs.net.run()
  File "/home/oda/ws/bluesky/bluesky/network/node.py", line 67, in run
    bs.sim.step()
  File "/home/oda/ws/bluesky/bluesky/simulation/simulation.py", line 82, in step
    simtime.preupdate()
  File "/home/oda/ws/bluesky/bluesky/core/simtime.py", line 67, in preupdate
    fun.trigger()
  File "/home/oda/ws/bluesky/bluesky/core/simtime.py", line 209, in call_timed
    self._callback()
  File "/home/oda/ws/bluesky/plugins/usepe_plugin.py", line 94, in preupdate
    usepesegments.preupdate()
  File "/home/oda/ws/bluesky/plugins/usepe_plugin.py", line 437, in preupdate
    updated, self.segments = self.dynamicSegments()
  File "/home/oda/ws/bluesky/plugins/usepe_plugin.py", line 322, in dynamicSegments
    self.segmentation_service.update_wind_strat( wind_file, False )  # strategic update rules based on wind data
  File "/home/oda/ws/bluesky/usepe/segmentation_service/segmentation_service.py", line 221, in update_wind_strat
    wind_data = misc.process_wind_data(
  File "/home/oda/ws/bluesky/usepe/segmentation_service/python/utils/misc.py", line 338, in process_wind_data
    windData.load()
  File "/home/oda/.conda/envs/usepeosm/lib/python3.8/site-packages/xarray/core/dataset.py", line 741, in load
    v.load()
  File "/home/oda/.conda/envs/usepeosm/lib/python3.8/site-packages/xarray/core/variable.py", line 461, in load
    self._data = np.asarray(self._data)
  File "/home/oda/.conda/envs/usepeosm/lib/python3.8/site-packages/xarray/core/indexing.py", line 653, in __array__
    self._ensure_cached()
  File "/home/oda/.conda/envs/usepeosm/lib/python3.8/site-packages/xarray/core/indexing.py", line 650, in _ensure_cached
    self.array = NumpyIndexingAdapter(np.asarray(self.array))
  File "/home/oda/.conda/envs/usepeosm/lib/python3.8/site-packages/xarray/core/indexing.py", line 623, in __array__
    return np.asarray(self.array, dtype=dtype)
  File "/home/oda/.conda/envs/usepeosm/lib/python3.8/site-packages/xarray/core/indexing.py", line 524, in __array__
    return np.asarray(array[self.key], dtype=None)
  File "/home/oda/.conda/envs/usepeosm/lib/python3.8/site-packages/xarray/coding/variables.py", line 72, in __array__
    return self.func(self.array)
  File "/home/oda/.conda/envs/usepeosm/lib/python3.8/site-packages/xarray/coding/variables.py", line 139, in _apply_mask
    data = np.asarray(data, dtype=dtype)
  File "/home/oda/.conda/envs/usepeosm/lib/python3.8/site-packages/xarray/core/indexing.py", line 524, in __array__
    return np.asarray(array[self.key], dtype=None)
  File "/home/oda/.conda/envs/usepeosm/lib/python3.8/site-packages/xarray/backends/netCDF4_.py", line 95, in __getitem__
    return indexing.explicit_indexing_adapter(
  File "/home/oda/.conda/envs/usepeosm/lib/python3.8/site-packages/xarray/core/indexing.py", line 815, in explicit_indexing_adapter
    result = raw_indexing_method(raw_key.tuple)
  File "/home/oda/.conda/envs/usepeosm/lib/python3.8/site-packages/xarray/backends/netCDF4_.py", line 108, in _getitem
    array = getitem(original_array, key)
  File "src/netCDF4/_netCDF4.pyx", line 4720, in netCDF4._netCDF4.Variable.__getitem__
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 42.3 GiB for an array with shape (12, 302, 1340, 2340) and data type float32
^CTraceback (most recent call last):
  File "/home/oda/ws/bluesky/bluesky/network/client.py", line 131, in update
    def update(self):

**Comment by oledahle** [comment]
Perhaps LUH can generate wind files for exercise 3 for a smaller area or with less granularity?

**Comment by Kara-Ro** [comment]
I leveraged the laziness of Xarray in the segmentationService and did a small cleanup. My memory requirements decreased approx. 3x. Could you try it? If the problems occurs while preprocessing the wind data it is possible because netCDF4 package in  interpolation_to_scalar_grid cannot do lazy loading of data. 
This should be possible to change to Xarray package.

**Comment by oledahle** [comment]
Ran again with the memory fix from Rostislav ([d4517d35f778](https://github.com/USEPE-SesarJU/bluesky/commit/d4517d35f7780f4b16abed511ca3b79bf277e615)). With the exercise 3 data it no longer produces an out-of-memory error, but it hangs directly after printing "Staring to process wind data." Python is using 4 GB of memory and 5% CPU, but nothing more is happening.

**Comment by oledahle** [comment]
From Rostislav:
 do not have this problem. I verified it for “scenario_1/USEPE_S1_3d” and “scenario_1/USEPE_S1_3d_nest01” files and everything was processed without problems.

Could you try to place breakpoint to process_wind_data function and look what exactly is stopping your code?

**Comment by oledahle** [comment]
The simulation crashes in process_wind_data() in misc.py, somwhere between line 353 and 365. (The subprocess simply dissapeared from the debugger, so I didn't catch the exact failure. This is the code in question:

 # # calculate scalar wind speed from staggered wind velocities
    # # scalar values in grid center -> interpolate into the grid center
    windData["speed"] = np.sqrt(
        np.power( windData["u"].interp( y=windData.coords["yv"], zu_3d=windData.coords["zw_3d"] ), 2 )
        +np.power(
            windData["v"].interp( x=windData.coords["xu"], zu_3d=windData.coords["zw_3d"] ), 2
        )
        # +np.power( windData["w"].interp( x=windData.coords["xu"], y=windData.coords["yv"] ), 2 )
    )

    windData["u"] = windData["u"][0,0,0]
    windData["v"] = windData["v"][0,0,0]
    # windData["w"] = windData["w"][0,0,0]

Maybe there is some operation here that doesn't work with the lazy loading of windData?

**Comment by Kara-Ro** [comment]
```
windData["u"] = windData["u"][0,0,0] 
windData["v"] = windData["v"][0,0,0] 
# windData["w"] = windData["w"][0,0,0]
```
is just a small cleanup. First thing would be to comment it out to verify that the problem is in the operation above.

Then, the evaluation of wind intensity can be separated to first interpolate the wind vector, and then do the rest. I am would suspect that the culprit will be in the interpolation. The interpolation in xarray requires scipy. I use scipy version 1.8.0.

If this doesn't work turn off lazy processing by uncommenting line 338 
`# windData.load()`

Some memory might be also saved by moving 
`windData.load()`
behind:
```
    windData["u"] = windData["u"][0, ...]
    windData["v"] = windData["v"][0, ...]
    # windData["w"] = windData["w"][0, ...]
```
Since I am not able to replicate the error I am not able to test it.

**Comment by oledahle** [comment]
I have narrowed down the problem to the operation that interpolates and calculates the wind values (line 353-358). The simulation runs fine if I reduce the operation to something simple (but wrong!) like this:  

windData["speed"] = np.sqrt(windData["u"])

**Comment by oledahle** [comment]
Question asked September 19:
Just one quick question today, while we wait for an update (or smaller files) from Felix: Why is the largest wind file (.nest version) used by the segmentation service?

I thought the largest file was only to be used by the wind_preprosess script, and the smaller file (with coarser resolution) used by the segmentation service during simulation?

**Comment by oledahle** [comment]
Answer from Miguel on September 20:
Let me be clear to avoid confusions, but I think you are right in what you said:
- Files that end with nestX are files for smaller regions with higher spatial resolution. Those files should be used for the wind_preprocess script, since the simulator should know the wind affecting the drone at each position with the highest resolution.
- Files without nestX for a larger region with coarser spatial resolution. To be used by the segmentation service, since its rules depend on maximum and averaged values within each segment.

**Comment by oledahle** [comment]
The simulator can now update the wind for the segments without crashing with this setting:
[Segmentation_service]
wind_path = exercise_3_surveillance/USEPE_S3_3d

Closing this issue.
