### ISSUE TITLE
ValueError when updating geovectoring rule

### ISSUE THREAD

**Issue by joakimrydberg** [USEPE-SesarJU/bluesky#35]
We see a recurring ValueError appearing during the execution of `dynamic_segments.updateGeovectoringRule()`.
It does not seem predictable when in a simulation the error will occur or for which simulation/dataset, which makes it difficult to debug. It seldom happens earlier than 10 min into the simulation, and can happen at the very end. This means several real hours before occurrence.
It can occur one time for a specific dataset, and the next not.

3 exceptions occurs as a result, in the following order:

```
Traceback (most recent call last):
  File "/home/tester/anaconda3/envs/usepeosm/lib/python3.8/site-packages/pandas/core/series.py", line 1108, in __setitem__
    self._set_with_engine(key, value)
  File "/home/tester/anaconda3/envs/usepeosm/lib/python3.8/site-packages/pandas/core/series.py", line 1178, in _set_with_engine
    loc = self.index.get_loc(key)
  File "/home/tester/anaconda3/envs/usepeosm/lib/python3.8/site-packages/pandas/core/indexes/multi.py", line 2898, in get_loc
    self._check_indexing_error(key)
  File "/home/tester/anaconda3/envs/usepeosm/lib/python3.8/site-packages/pandas/core/indexes/multi.py", line 2581, in _check_indexing_error
    raise InvalidIndexError(key)
pandas.errors.InvalidIndexError: u                         v                        key
A20924832                 A305994739               0      False
                          A20924851                0      False
                          A266186744               0      False
                          B20924832                0      False
A20924843                 A933612239               0      False
                                                          ...  
A269228499_A2707960224_2  A2707960224              0      False
A268777545_A269228499_1   A268777545               0      False
                          A268777545_A269228499_2  0      False
A268777545_A269228499_2   A268777545_A269228499_1  0      False
                          A269228499               0      False
Name: segment, Length: 187576, dtype: bool

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tester/anaconda3/envs/usepeosm/lib/python3.8/site-packages/pandas/core/internals/blocks.py", line 972, in setitem
    casted = np_can_hold_element(values.dtype, value)
  File "/home/tester/anaconda3/envs/usepeosm/lib/python3.8/site-packages/pandas/core/dtypes/cast.py", line 2024, in np_can_hold_element
    raise LossySetitemError
pandas.core.dtypes.cast.LossySetitemError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "BlueSky.py", line 134, in <module>
    main()
  File "BlueSky.py", line 101, in main
    bs.net.run()
  File "/home/tester/ws/bluesky_3/bluesky/network/node.py", line 67, in run
    bs.sim.step()
  File "/home/tester/ws/bluesky_3/bluesky/simulation/simulation.py", line 82, in step
    simtime.preupdate()
  File "/home/tester/ws/bluesky_3/bluesky/core/simtime.py", line 67, in preupdate
    fun.trigger()
  File "/home/tester/ws/bluesky_3/bluesky/core/simtime.py", line 209, in call_timed
    self._callback()
  File "/home/tester/ws/bluesky_3/plugins/usepe_plugin.py", line 96, in preupdate
    usepesegments.preupdate()
  File "/home/tester/ws/bluesky_3/plugins/usepe_plugin.py", line 563, in preupdate
    usepegraph.graph, self.segments = dynamicSegments( usepegraph.graph, usepeconfig, self.segments, deleted_segments=None )
  File "/home/tester/ws/bluesky_3/usepe/city_model/dynamic_segments.py", line 383, in dynamicSegments
    G = updateGeovectoringRule( G, segments_df )
  File "/home/tester/ws/bluesky_3/usepe/city_model/dynamic_segments.py", line 298, in updateGeovectoringRule
    edges['speed'][cond] = edges[cond].apply( lambda x:
  File "/home/tester/anaconda3/envs/usepeosm/lib/python3.8/site-packages/pandas/core/series.py", line 1159, in __setitem__
    self._set_values(indexer, value)
  File "/home/tester/anaconda3/envs/usepeosm/lib/python3.8/site-packages/pandas/core/series.py", line 1218, in _set_values
    self._mgr = self._mgr.setitem(indexer=key, value=value)
  File "/home/tester/anaconda3/envs/usepeosm/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 389, in setitem
    return self.apply("setitem", indexer=indexer, value=value)
  File "/home/tester/anaconda3/envs/usepeosm/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 348, in apply
    applied = getattr(b, f)(**kwargs)
  File "/home/tester/anaconda3/envs/usepeosm/lib/python3.8/site-packages/pandas/core/internals/blocks.py", line 976, in setitem
    return nb.setitem(indexer, value)
  File "/home/tester/anaconda3/envs/usepeosm/lib/python3.8/site-packages/pandas/core/internals/blocks.py", line 985, in setitem
    values[indexer] = casted
ValueError: could not broadcast input array from shape (0,6) into shape (0,)
```

Attached:
[Full terminal output](https://github.com/USEPE-SesarJU/bluesky/files/9876813/terminal_output.txt)

**Comment by jbueno-nommon** [comment]
This issue should be fixed in the commit f3066ebcacbbd2a63f346294ae848a807f7b2749
Let us know if it works

**Comment by joakimrydberg** [comment]
Great. Thank you.
I will run a simulation to test.

**Comment by joakimrydberg** [comment]
Simulation successful.
Closing issue
